// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cloud_logic = 'enable';
var aws_cloud_logic_custom = [{"id":"m97x7hmds3","name":"Pets","description":"","endpoint":"https://m97x7hmds3.execute-api.us-east-2.amazonaws.com/Development","region":"us-east-2","paths":["/items","/items/123"]}];
var aws_cognito_identity_pool_id = 'us-east-2:75ef808c-3280-4bfb-baff-05ab9604a26c';
var aws_cognito_region = 'us-east-2';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'elevate-hosting-mobilehub-1760708160';
var aws_content_delivery_bucket_region = 'us-east-2';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd28r1htcj5q8dq.cloudfront.net';
var aws_dynamodb = 'enable';
var aws_dynamodb_all_tables_region = 'us-east-2';
var aws_dynamodb_table_schemas = [{"tableName":"elevate-mobilehub-1760708160-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-east-2","hashKey":"userId","rangeKey":"petId"}];
var aws_mobile_analytics_app_id = '91c13cc97b5147b68d593e61f0bbfbe9';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '3f36cfa6-b64c-4b5f-a88f-f804b58b914d';
var aws_project_name = 'elevate';
var aws_project_region = 'us-east-2';
var aws_resource_bucket_name = 'elevate-deployments-mobilehub-1760708160';
var aws_resource_name_prefix = 'elevate-mobilehub-1760708160';
var aws_sign_in_enabled = 'enable';
var aws_user_files = 'enable';
var aws_user_files_s3_bucket = 'elevate-userfiles-mobilehub-1760708160';
var aws_user_files_s3_bucket_region = 'us-east-2';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-2_7wZC9TBA3';
var aws_user_pools_mfa_type = 'ON';
var aws_user_pools_web_client_id = '5geqg2e2rmhpgdc45kscjq8cst';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
