// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"m97x7hmds3","name":"Pets","description":"","endpoint":"https://m97x7hmds3.execute-api.us-east-2.amazonaws.com/Development","region":"us-east-2","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-2:75ef808c-3280-4bfb-baff-05ab9604a26c',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'elevate-hosting-mobilehub-1760708160',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd28r1htcj5q8dq.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-2',
    'aws_dynamodb_table_schemas': [{"tableName":"elevate-mobilehub-1760708160-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-east-2","hashKey":"userId","rangeKey":"petId"}],
    'aws_mobile_analytics_app_id': '91c13cc97b5147b68d593e61f0bbfbe9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3f36cfa6-b64c-4b5f-a88f-f804b58b914d',
    'aws_project_name': 'elevate',
    'aws_project_region': 'us-east-2',
    'aws_resource_bucket_name': 'elevate-deployments-mobilehub-1760708160',
    'aws_resource_name_prefix': 'elevate-mobilehub-1760708160',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'elevate-userfiles-mobilehub-1760708160',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_7wZC9TBA3',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5geqg2e2rmhpgdc45kscjq8cst',
}

export default awsmobile;
